[package]
name = "suiprediction"
version = "0.0.1"

[dependencies]
Sui = { local = "../../../crates/sui-framework/packages/sui-framework" }
SupraOracle = {local = "../supra-svalue-feed-framework" }

[addresses]
suiprediction = "0x0"
